name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
    - name: Build
      run: g++ -std=c++17 -o main HUST.cpp
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
